# Site settings
title: Nimiq Community
email: community@nimiq.com
description: "A compendium of community Nimiq-related content"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nimiq.community"
twitter_username: nimiq
github_username:  nimiq

# Build settings
markdown: kramdown

paginate: 100
paginate_path: "academy/page:num"
encoding: utf-8
# Gems
# gems: [jekyll-paginate]
